### PR TITLE
add current browser versions for desktops, add specs

### PR DESCRIPTION
**Pull request by mycargus**

### CODE REVIEW

**Comment by mycargus** [comment]
I didn't bump the version as I don't know your gem version bump workflow. 😃

**Comment by bootstraponline** [comment]
> I didn't bump the version as I don't know your gem version bump workflow. 😃

I just run thor bump before release. :) `thor list` shows all the commands.

Thanks for the PR!

**Comment by mycargus** [comment]
Oh right on. Glad to contribute! Thanks for the gem.

**Comment by bootstraponline** [comment]
I updated the files again via `thor gen` and pushed v3.0.1 to RubyGems. You should be all set for accessing the new platforms.

**Pull request merged**
